{
    'name': "Accounting Reports Customizations",
    'description': "Accounting Reports Customizations",
    'category': 'customization',
    'author' : 'Hamza Naveed',
    'sequence': 10,
    'version': '1.0',
    'depends': [ 'account_reports' ], 
    'data': [],
    'demo' : [],
    'qweb' : [],
    'website' : '',
    'installable' : True, 
    'application' : False,
    'auto_install' : False,
    'license': 'LGPL-3',
}